//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuizSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendListForStudnet
    {
        public int FID { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> teacherid { get; set; }
        public Nullable<System.DateTime> timedate { get; set; }
        public int friendlist { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
