//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuizSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    using OnlineQuizSystem.Models;

    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Categories = new HashSet<Category>();
            this.FriendListForStudnets = new HashSet<FriendListForStudnet>();
        }
    
        public int TeacherID { get; set; }
        //[Required(ErrorMessage ="Enter your full name")]
        //[Display(Name ="Full Name")]
        public string FullName { get; set; }
        //[Required(ErrorMessage = "Enter your user name")]
        //[Display(Name = "User Name")]
        public string TeacherName { get; set; }
        public string Email { get; set; }
        public string Passwords { get; set; }
        public string Institute { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendListForStudnet> FriendListForStudnets { get; set; }
    }
}
